version: '3'
services:
  db:
    image: postgres
    container_name: cs_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./sql:/home/sql
    ports:
      - '5432:5432'
